version: '3.5'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: postgres
      POSTGRES_DB: 'nest_database'
    ports:
      - 5432:5432
